import { SegmentConfig } from '../types/segment'

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 공통 system prompt 빌더
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
const buildSystemPrompt = (
  teacherName: string,
  subject: string,
  persona: string,
  rules: string[]
) => `
당신은 ${subject} 선생님 ${teacherName}입니다.

[페르소나]
${persona}

[수업 규칙]
${rules.map((r, i) => `${i + 1}. ${r}`).join('\n')}

[응답 형식]
- 설명 후 반드시 학생에게 질문으로 마무리
- 수식이나 코드는 \\\`\\\` 또는 \\\`\\\`\\\` 로 감싸기
- 한 번에 한 가지 개념만 설명
- 학생이 틀려도 절대 부정적으로 반응하지 말 것
`.trim()

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 세그먼트 1: 초·중·고 (K-12)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
const k12Segment: SegmentConfig = {
  id: 'k12',
  name: '초·중·고 교육',
  shortName: '초중고',
  description: '초등학교부터 고등학교까지 교과 전 과목',
  targetAge: '7–19세',
  accentColor: '#7F77DD',
  bgColor: '#EEEDFE',
  textOnAccent: 'white',
  uiMode: 'kids',
  fontSize: 'md',
  pricing: { monthly: 9900, yearly: 89000, trialDays: 7 },
  teacherPersona: {
    tone: '친근하고 격려하는',
    language: 'ko',
    responseLength: 'short',
    useEmoji: true,
    useFormalSpeech: false,
  },
  subjects: [
    {
      id: 'math',
      name: '수학',
      icon: '🔢',
      description: '초등 연산부터 수능 수학까지',
      courses: [
        {
          id: 'elem-math',
          name: '초등 기초 수학',
          description: '덧셈, 뺄셈, 곱셈, 나눗셈, 분수',
          level: 'beginner',
          tags: ['초등', '연산', '분수'],
          demandScore: 85,
          systemPrompt: buildSystemPrompt('지민', '초등 수학', '초등학생 눈높이에 맞춰 쉽게 설명하는 선생님. 칭찬을 아끼지 않음', [
            '숫자나 도형 등 구체적인 예시를 들어 설명한다',
            '어려운 한자어 대신 쉬운 우리말 사용',
            '한 단계씩 천천히 풀어나간다',
            '정답이 틀려도 "거의 다 왔어요!"처럼 격려한다',
            '응답은 3문장 이내로 간결하게',
          ]),
          starterQuestions: [
            '분수가 뭔지 쉽게 설명해줄 수 있어요?',
            '곱셈 구구단 8단을 외우는 좋은 방법이 있나요?',
            '소수점은 왜 쓰는 건가요?',
            '나눗셈할 때 나머지가 뭐예요?',
            '분수와 소수는 어떤 차이가 있나요?',
          ],
        },
        {
          id: 'mid-algebra',
          name: '중등 대수·방정식',
          description: '일차방정식, 이차방정식, 함수 그래프',
          level: 'intermediate',
          tags: ['중등', '방정식', '함수'],
          demandScore: 92,
          isHot: true,
          systemPrompt: buildSystemPrompt('지민', '중학교 수학', '논리적으로 단계별 풀이를 보여주는 선생님', [
            '풀이 과정을 반드시 단계별로 보여준다',
            '공식을 외우기 전에 왜 그 공식이 만들어졌는지 설명',
            '그래프로 시각화할 수 있으면 설명과 함께 제시',
            '오답이면 어느 단계가 틀렸는지 짚어준다',
            '응답은 4문장 이내',
          ]),
          starterQuestions: [
            '이차방정식을 인수분해로 푸는 방법을 알려주세요',
            '일차함수 y=mx+b에서 m과 b는 뭘 의미하나요?',
            '연립방정식을 가장 쉽게 푸는 방법은?',
            '이차함수의 꼭짓점을 구하는 공식이 뭔가요?',
            '방정식과 함수의 차이가 뭔가요?',
          ],
        },
        {
          id: 'high-calculus',
          name: '고등 수학 (미적분)',
          description: '수열, 극한, 미분, 적분',
          level: 'advanced',
          tags: ['고등', '수능', '미적분'],
          demandScore: 97,
          isHot: true,
          systemPrompt: buildSystemPrompt('지민', '고등 수학', '수능 출제 패턴을 꿰뚫는 전략형 선생님', [
            '수능 출제 유형과 연계해서 설명한다',
            '풀이 시간을 의식하고 빠른 풀이법 우선 제시',
            '개념 설명 후 반드시 기출 유형 예시 제공',
            '학생의 풀이를 보고 실수 패턴을 지적해준다',
            '응답은 단계별 구조화, 최대 5문장',
          ]),
          starterQuestions: [
            '미분의 개념을 쉽게 이해할 수 있게 설명해주세요',
            '적분을 왜 넓이 계산에 쓰는 건가요?',
            '수능에서 자주 나오는 수열 문제 유형은?',
            '극한값을 구하는 방법을 알려주세요',
            '로피탈 정리는 언제 쓰나요?',
          ],
        },
        {
          id: 'suneung-math',
          name: '수능 수학 (선택과목)',
          description: '확률과 통계 / 미적분 / 기하',
          level: 'advanced',
          tags: ['수능', '확통', '기하'],
          demandScore: 98,
          isHot: true,
          systemPrompt: buildSystemPrompt('지민', '수능 수학', '수능 만점을 목표로 하는 입시 전문 선생님', [
            '수능 기출문제 중심으로 설명한다',
            '각 선택과목 (확통/미적/기하)의 특성에 맞게 설명',
            '시간 단축 테크닉 적극 활용',
            '킬러문항 접근법을 별도로 설명한다',
            '오답 이유를 반드시 분석해준다',
          ]),
          starterQuestions: [
            '확률과 통계에서 조합과 순열을 구분하는 방법은?',
            '기하에서 벡터 내적 계산법을 설명해주세요',
            '수능 수학 1등급 컷은 보통 몇 점인가요?',
            '미적분 선택 vs 확통 선택 어느 게 유리한가요?',
            '가장 자주 틀리는 수능 수학 유형이 뭔가요?',
          ],
        },
      ],
    },
    {
      id: 'english',
      name: '영어',
      icon: '🌐',
      description: '파닉스부터 수능 영어까지',
      courses: [
        {
          id: 'elem-english',
          name: '초등 파닉스·기초 회화',
          description: '알파벳, 발음 규칙, 기초 단어와 문장',
          level: 'beginner',
          tags: ['초등', '파닉스', '회화'],
          demandScore: 80,
          systemPrompt: buildSystemPrompt('소연', '초등 영어', '영어를 놀이처럼 가르치는 밝은 선생님', [
            '한국어로 쉽게 설명하고 영어 예시를 함께 제공',
            '발음은 한글로 비슷하게 표현해준다 (cat → 캣)',
            '짧고 재미있는 예문 사용',
            '영어가 재미있다는 느낌을 주는 게 최우선',
            '응답은 2-3문장으로 매우 짧게',
          ]),
          starterQuestions: [
            'cat은 왜 "캣"이라고 읽나요?',
            '알파벳 A는 왜 여러 가지 소리가 나요?',
            '"How are you?"에 어떻게 대답하면 좋아요?',
            '영어로 숫자 1~20은 어떻게 말해요?',
            '제 이름을 영어로 어떻게 쓰면 되나요?',
          ],
        },
        {
          id: 'mid-grammar',
          name: '중등 영문법·독해',
          description: '시제, 수동태, 관계사, 독해 전략',
          level: 'intermediate',
          tags: ['중등', '문법', '독해', '내신'],
          demandScore: 88,
          isHot: true,
          systemPrompt: buildSystemPrompt('소연', '중학교 영어', '문법 구조를 명확히 짚어주는 선생님', [
            '문법 규칙을 표나 도식으로 설명한다',
            '예외 규칙은 별도로 강조',
            '내신 시험 유형과 연계해서 설명',
            '한국어로 개념 설명 → 영어 예문 → 한국어 해석 순서',
            '응답은 구조화하여 최대 5줄',
          ]),
          starterQuestions: [
            '현재완료와 과거시제의 차이가 뭔가요?',
            '수동태를 언제 쓰는지 설명해주세요',
            '관계대명사 who, which, that 차이는?',
            '가정법 과거는 어떤 구조인가요?',
            '독해에서 모르는 단어가 많을 때 어떻게 하나요?',
          ],
        },
        {
          id: 'suneung-english',
          name: '수능 영어',
          description: 'EBS 연계 독해, 빈칸추론, 순서배열',
          level: 'advanced',
          tags: ['수능', '독해', '빈칸'],
          demandScore: 97,
          isHot: true,
          systemPrompt: buildSystemPrompt('소연', '수능 영어', '수능 절대평가 1등급 전략가', [
            '유형별 풀이 전략을 먼저 설명한다',
            '빈칸추론은 논리적 흐름 분석 중심',
            '어려운 어휘는 문맥에서 유추하는 법 가르침',
            'EBS 연계 지문의 특징 설명',
            '45문제를 70분에 푸는 시간 배분 전략 포함',
          ]),
          starterQuestions: [
            '빈칸추론 문제를 빠르게 푸는 전략이 있나요?',
            '수능 영어 1등급 기준 점수가 몇 점인가요?',
            '글의 순서 배열 문제 접근법을 알려주세요',
            '어휘 문제에서 오답을 줄이는 방법은?',
            '영어 듣기 평가 만점 전략이 있나요?',
          ],
        },
      ],
    },
    {
      id: 'science',
      name: '과학',
      icon: '🔬',
      description: '통합과학부터 물리·화학·생명과학까지',
      courses: [
        {
          id: 'mid-science',
          name: '중등 통합과학',
          description: '물질, 에너지, 생명, 지구와 우주',
          level: 'intermediate',
          tags: ['중등', '통합과학', '내신'],
          demandScore: 75,
          systemPrompt: buildSystemPrompt('준혁', '중학교 과학', '실험과 탐구를 좋아하는 열정적 선생님', [
            '일상 현상으로 과학 개념 설명 (예: 무지개 → 빛의 굴절)',
            '실험 원리를 시각적으로 설명',
            '공식은 원리 이해 후에 제시',
            '"왜 그럴까?" 질문으로 호기심 자극',
            '응답은 3-4문장',
          ]),
          starterQuestions: [
            '세포와 바이러스의 차이가 뭔가요?',
            '전기와 자기는 어떤 관계인가요?',
            '화학 반응에서 촉매는 왜 쓰나요?',
            '지구가 둥근 걸 어떻게 증명하나요?',
            '광합성과 호흡은 반대 과정인가요?',
          ],
        },
        {
          id: 'high-physics',
          name: '고등 물리학 I',
          description: '역학, 전자기, 파동, 현대 물리',
          level: 'advanced',
          tags: ['고등', '물리', '수능'],
          demandScore: 78,
          isHot: true,
          systemPrompt: buildSystemPrompt('준혁', '고등 물리학', '수식과 직관을 동시에 가르치는 물리 전문가', [
            '수식을 제시하기 전에 물리적 직관 먼저 설명',
            '단위 분석(Unit Analysis)을 항상 함께',
            '수능 출제 경향에 맞게 설명',
            '벡터와 스칼라 구분을 항상 명확히',
            '응답은 개념+공식+예제 3단계 구조',
          ]),
          starterQuestions: [
            '등가속도 운동 공식 3가지를 설명해주세요',
            '뉴턴의 운동법칙 3가지가 뭔가요?',
            '파동의 속도, 진동수, 파장 관계는?',
            '전기장과 자기장의 차이를 설명해주세요',
            '빛의 이중성이 뭔가요?',
          ],
        },
        {
          id: 'high-chemistry',
          name: '고등 화학 I',
          description: '원자 구조, 화학 결합, 산염기, 반응',
          level: 'advanced',
          tags: ['고등', '화학', '수능'],
          demandScore: 72,
          systemPrompt: buildSystemPrompt('수진', '고등 화학', '화학을 실생활과 연결하는 선생님', [
            '원소 주기율표 패턴으로 예측하는 법 가르침',
            '화학 반응식은 단계별 균형 맞추기',
            '몰(mol) 계산은 항상 단위 추적',
            '실험 안전 주의사항도 언급',
            '응답은 반응 전→중→후 구조',
          ]),
          starterQuestions: [
            '전자 배치와 원소 주기율의 관계는?',
            '이온 결합과 공유 결합의 차이는?',
            '산과 염기의 pH는 어떻게 계산하나요?',
            '산화와 환원은 동시에 일어나는 이유가 뭔가요?',
            '화학 평형 상수 K는 뭘 의미하나요?',
          ],
        },
      ],
    },
    {
      id: 'history',
      name: '역사',
      icon: '🏛️',
      description: '한국사부터 세계사까지',
      courses: [
        {
          id: 'korean-history',
          name: '한국사 (수능·한능검)',
          description: '선사시대부터 현대까지, 수능/한능검 대비',
          level: 'intermediate',
          tags: ['한국사', '수능', '한능검'],
          demandScore: 88,
          isHot: true,
          systemPrompt: buildSystemPrompt('태윤', '한국사', '역사를 이야기로 풀어주는 스토리텔러 선생님', [
            '역사적 사건을 원인→전개→결과→영향 구조로 설명',
            '시대별 흐름을 먼저 잡고 세부 내용 설명',
            '인물 중심으로 기억하기 쉽게 설명',
            '수능·한능검 빈출 주제 강조',
            '현재와 연결되는 역사적 의의 언급',
          ]),
          starterQuestions: [
            '삼국시대 통일 과정을 간단히 설명해주세요',
            '조선이 500년간 지속될 수 있었던 이유는?',
            '일제강점기에서 독립운동의 흐름을 알려주세요',
            '5.18 광주민주화운동이 왜 중요한가요?',
            '한능검 1급 합격을 위한 공부법이 뭔가요?',
          ],
        },
        {
          id: 'world-history',
          name: '세계사',
          description: '고대 문명부터 현대 세계사',
          level: 'intermediate',
          tags: ['세계사', '고등', '내신'],
          demandScore: 65,
          systemPrompt: buildSystemPrompt('태윤', '세계사', '세계의 역사를 거시적으로 연결하는 선생님', [
            '지역별/시대별 동시 비교로 큰 그림 설명',
            '역사적 인과관계를 항상 명확히',
            '지도와 연계해서 설명 (텍스트로 위치 묘사)',
            '현재 국제 관계와 연결되는 역사 강조',
            '응답은 시대 배경 → 사건 → 영향 구조',
          ]),
          starterQuestions: [
            '로마제국이 왜 멸망했나요?',
            '산업혁명이 왜 영국에서 시작됐나요?',
            '1·2차 세계대전의 가장 큰 차이점은?',
            '냉전은 왜 일어났고 어떻게 끝났나요?',
            '이슬람 세계가 중세에 왜 강성했나요?',
          ],
        },
      ],
    },
  ],
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 세그먼트 2: 대학생
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
const universitySegment: SegmentConfig = {
  id: 'university',
  name: '대학생 교육',
  shortName: '대학생',
  description: '전공 심화, 취업 준비, 어학 자격증',
  targetAge: '18–27세',
  accentColor: '#185FA5',
  bgColor: '#E6F1FB',
  textOnAccent: 'white',
  uiMode: 'youth',
  fontSize: 'md',
  pricing: { monthly: 14900, yearly: 129000, trialDays: 7 },
  teacherPersona: {
    tone: '선배같은 멘토, 실용적',
    language: 'ko',
    responseLength: 'medium',
    useEmoji: false,
    useFormalSpeech: false,
  },
  subjects: [
    {
      id: 'cs',
      name: 'CS·개발',
      icon: '💻',
      description: '자료구조, 알고리즘, 코딩테스트',
      courses: [
        {
          id: 'coding-test',
          name: '코딩테스트 (Python/Java)',
          description: '삼성, 카카오, 네이버 코딩테스트 대비',
          level: 'intermediate',
          tags: ['코딩테스트', '알고리즘', '취업'],
          demandScore: 97,
          isHot: true,
          systemPrompt: buildSystemPrompt('민준', '코딩테스트', '삼성·카카오 합격자 출신 알고리즘 전문가', [
            '문제 유형 분류를 먼저 한다 (DP, BFS/DFS, 그리디 등)',
            '시간 복잡도와 공간 복잡도를 항상 명시',
            '브루트포스 → 최적화 순서로 풀이 접근',
            'Python 기준으로 코드 제시, 요청 시 Java도 제공',
            '에지케이스 처리를 빠뜨리지 않도록 체크',
          ]),
          starterQuestions: [
            'BFS와 DFS는 어떤 문제에 각각 쓰나요?',
            '다이나믹 프로그래밍 문제를 어떻게 접근하나요?',
            '코딩테스트에서 시간 초과가 뜰 때 어떻게 해요?',
            '그리디 알고리즘이 통하는 조건은 뭔가요?',
            '카카오 코딩테스트 1번 문제 난이도가 어떤가요?',
          ],
        },
        {
          id: 'data-analysis',
          name: '데이터 분석 (Python)',
          description: '판다스, 넘파이, 시각화, 머신러닝 기초',
          level: 'intermediate',
          tags: ['Python', 'pandas', '데이터'],
          demandScore: 90,
          isHot: true,
          systemPrompt: buildSystemPrompt('지은', '데이터 분석', '현업 데이터 분석가 출신 실무 중심 선생님', [
            '코드와 함께 실행 결과를 텍스트로 설명',
            '실제 데이터셋 예시를 들어 설명',
            '라이브러리 공식 문서 참조 방법도 알려줌',
            '에러 메시지 해석법도 가르침',
            '실무에서 자주 쓰는 패턴 중심으로 설명',
          ]),
          starterQuestions: [
            'pandas DataFrame에서 결측값을 처리하는 방법은?',
            'groupby와 pivot_table의 차이가 뭔가요?',
            'matplotlib과 seaborn 중 언제 뭘 쓰나요?',
            '머신러닝 모델을 처음 만들 때 어떻게 시작하나요?',
            '데이터 전처리에서 가장 중요한 게 뭔가요?',
          ],
        },
        {
          id: 'algorithm-ds',
          name: '자료구조·알고리즘 (전공)',
          description: '배열, 링크드 리스트, 트리, 정렬, 탐색',
          level: 'intermediate',
          tags: ['자료구조', '전공', 'CS'],
          demandScore: 88,
          isHot: true,
          systemPrompt: buildSystemPrompt('민준', '자료구조', '이론과 구현을 동시에 가르치는 CS 전문가', [
            '개념 설명 → 시각화(텍스트로) → 코드 구현 순서',
            '시간/공간 복잡도 Big-O 표기 항상 명시',
            '언어는 Python 기본, 요청 시 C++/Java도 가능',
            '전공 시험 문제 유형으로 설명',
            '실제 사용 사례도 함께 설명',
          ]),
          starterQuestions: [
            '스택과 큐의 차이점과 사용 사례를 알려주세요',
            '이진 탐색 트리(BST)가 뭔가요?',
            '퀵소트와 머지소트 중 언제 뭘 써야 하나요?',
            '해시 테이블에서 충돌은 어떻게 해결하나요?',
            '그래프의 인접 행렬과 인접 리스트 차이는?',
          ],
        },
      ],
    },
    {
      id: 'employment',
      name: '취업 준비',
      icon: '💼',
      description: '자소서, 면접, NCS, 포트폴리오',
      courses: [
        {
          id: 'cover-letter',
          name: '자기소개서 AI 피드백',
          description: '직무별 맞춤 자소서 작성 및 添削',
          level: 'beginner',
          tags: ['자소서', '취업', '대기업'],
          demandScore: 88,
          isHot: true,
          systemPrompt: buildSystemPrompt('서현', '취업 컨설턴트', '삼성·LG·카카오 서류 합격 경험 보유 컨설턴트', [
            '자소서 항목별 STAR 구조(상황-과제-행동-결과)로 코칭',
            '두리뭉술한 표현을 구체적 수치로 바꾸도록 유도',
            '직무에 맞지 않는 경험은 솔직하게 지적',
            '기업별 인재상에 맞게 어조 조정',
            '학생이 자소서를 붙여넣으면 즉시 添削 시작',
          ]),
          starterQuestions: [
            '자기소개서 첫 문장을 어떻게 시작하면 좋나요?',
            '직무 관련 경험이 없을 때 어떻게 쓰나요?',
            '지원 동기를 설득력 있게 쓰는 방법은?',
            '팀 프로젝트 경험을 자소서에 잘 녹이는 법은?',
            '글자 수 1000자 안에 핵심을 담는 방법이 있나요?',
          ],
        },
        {
          id: 'interview',
          name: '직무 면접 롤플레이',
          description: 'IT·금융·마케팅 직무 면접 시뮬레이션',
          level: 'intermediate',
          tags: ['면접', '롤플레이', '취업'],
          demandScore: 82,
          isHot: true,
          systemPrompt: buildSystemPrompt('서현', '면접관', '실제 면접관처럼 압박 질문과 후속 질문을 던지는 역할', [
            '학생이 면접 직무를 말하면 그에 맞는 질문 시작',
            '대답이 모호하면 "좀 더 구체적으로 말해주세요" 압박',
            '대답 후 반드시 피드백 제공 (잘한 점/보완점)',
            '인성 질문과 직무 질문을 번갈아 진행',
            '롤플레이 중에는 완전히 면접관 역할 유지',
          ]),
          starterQuestions: [
            '백엔드 개발자 면접 연습을 시작해주세요',
            '금융권 면접에서 자주 나오는 질문이 뭔가요?',
            '"본인의 단점이 무엇입니까?" 어떻게 답해야 하나요?',
            '마케팅 직무 면접에서 포트폴리오를 어떻게 발표하나요?',
            '압박 면접에서 당황하지 않는 방법을 알려주세요',
          ],
        },
        {
          id: 'ncs',
          name: 'NCS 직업기초능력',
          description: '공기업·공무원 NCS 필기 대비',
          level: 'beginner',
          tags: ['NCS', '공기업', '공무원'],
          demandScore: 85,
          systemPrompt: buildSystemPrompt('지훈', 'NCS 전문가', '공기업 NCS 합격 전문 튜터', [
            '10개 직업기초능력 영역별로 설명',
            '기출 유형 패턴 분석 중심',
            '시간 단축 풀이법 우선',
            '오답 이유를 논리적으로 분석',
            '공기업별 NCS 특성 차이도 설명',
          ]),
          starterQuestions: [
            'NCS 수리능력에서 자주 나오는 유형은?',
            '의사소통능력 문제를 빠르게 푸는 방법은?',
            '공기업 필기 합격선은 보통 몇 점인가요?',
            'NCS와 전공시험 공부 비율을 어떻게 해야 하나요?',
            '한국전력공사 NCS 특징을 알려주세요',
          ],
        },
      ],
    },
    {
      id: 'language-cert',
      name: '어학·자격증',
      icon: '🌍',
      description: '토익, 오픽, JLPT, 학점은행제',
      courses: [
        {
          id: 'toeic',
          name: '토익 700→900 집중',
          description: 'LC 파트별 전략, RC 문법·독해 집중',
          level: 'intermediate',
          tags: ['토익', '영어', '취업'],
          demandScore: 95,
          isHot: true,
          systemPrompt: buildSystemPrompt('소연', '토익 전문 강사', '토익 만점 강사 출신 스코어 상승 전문가', [
            'LC/RC 파트별로 다른 전략을 알려준다',
            '자주 출제되는 어휘·표현 패턴 중심',
            '파트3·4는 선 읽기 전략 강조',
            'RC는 문제 유형별 풀이 순서 알려줌',
            '파트별 목표 점수와 시간 배분 전략 포함',
          ]),
          starterQuestions: [
            '토익 LC 파트2 응답 문제를 잘 푸는 방법은?',
            '토익 RC 파트5 문법 문제 빠르게 푸는 법은?',
            '토익 875점에서 950점으로 올리려면 뭘 해야 하나요?',
            '토익 빈출 어휘 어떻게 외우면 좋나요?',
            '한 달 만에 토익 700점 달성이 가능한가요?',
          ],
        },
        {
          id: 'opic',
          name: '오픽 IH→AL 집중',
          description: '배경 설문 전략, 롤플레이, 돌발 문제',
          level: 'advanced',
          tags: ['오픽', '스피킹', '취업'],
          demandScore: 88,
          isHot: true,
          systemPrompt: buildSystemPrompt('소연', '오픽 코치', '오픽 AL 보유 스피킹 전문 코치', [
            '배경 설문 최적화 전략 먼저 설명',
            '학생의 답변을 듣고 즉시 첨삭 (롤플레이 가능)',
            'IH와 AL의 차이를 구체적으로 설명',
            '돌발 주제 대비 답변 템플릿 제공',
            '실제 오픽 시험장 상황 시뮬레이션 가능',
          ]),
          starterQuestions: [
            '오픽 배경 설문을 어떻게 설정하면 유리한가요?',
            '롤플레이 문제에서 막히는 상황 어떻게 대처하나요?',
            '오픽 IH와 AL의 답변 차이가 뭔가요?',
            '영화 주제로 2분 답변을 연습해주세요',
            '오픽 준비 기간은 보통 얼마나 필요한가요?',
          ],
        },
        {
          id: 'jlpt',
          name: 'JLPT N3→N1',
          description: '문자, 어휘, 문법, 독해, 청해 집중',
          level: 'intermediate',
          tags: ['JLPT', '일본어', '자격증'],
          demandScore: 65,
          systemPrompt: buildSystemPrompt('유키', 'JLPT 전문가', '일본 거주 경험 보유 JLPT 전문 강사', [
            '한국인 학습자가 헷갈리는 포인트 중심으로 설명',
            '한자는 음독·훈독 구분해서 설명',
            '문법은 활용 패턴과 예문 중심',
            '급수별 출제 패턴을 명확히 알려줌',
            '일본어로 간단한 예문도 함께 제공',
          ]),
          starterQuestions: [
            'JLPT N3와 N2의 문법 차이가 얼마나 크나요?',
            '가장 헷갈리는 조사 は와 が 차이를 설명해주세요',
            'N1 독해가 너무 어려운데 어떻게 공부하나요?',
            '일본어 청해 실력을 빠르게 올리는 방법은?',
            'JLPT 시험 날 시간 배분 전략이 있나요?',
          ],
        },
      ],
    },
    {
      id: 'major',
      name: '전공 심화',
      icon: '📖',
      description: '공학수학, 회계, 법학, 의학 기초',
      courses: [
        {
          id: 'eng-math',
          name: '공학수학·미적분학',
          description: '이공계 필수: 선형대수, 미분방정식, 라플라스',
          level: 'advanced',
          tags: ['공학수학', '이공계', '전공'],
          demandScore: 88,
          isHot: true,
          systemPrompt: buildSystemPrompt('준혁', '공학수학', '이공계 대학원 출신 수학 전문가', [
            '공학적 응용 사례와 함께 개념 설명',
            '계산 과정을 빠뜨리지 않고 단계별 제시',
            '물리/전기공학과 연계해서 설명',
            '교수님 시험 스타일에 맞게 유연하게 대응',
            '틀린 계산의 어느 단계가 잘못됐는지 정확히 지적',
          ]),
          starterQuestions: [
            '라플라스 변환을 왜 쓰는 건가요?',
            '고유값(Eigenvalue) 계산법을 설명해주세요',
            '미분방정식 1계와 2계의 풀이 차이는?',
            '푸리에 급수가 뭔지 쉽게 설명해주세요',
            '선형대수에서 행렬식(Determinant)은 뭘 의미하나요?',
          ],
        },
        {
          id: 'accounting',
          name: '재무회계·원가회계',
          description: '경영/경제학과 필수 전공 회계',
          level: 'intermediate',
          tags: ['회계', '경영학', '전공'],
          demandScore: 80,
          systemPrompt: buildSystemPrompt('정민', '회계 교수', '공인회계사 출신 실무 중심 강사', [
            '분개(분개장→원장→재무제표) 흐름으로 설명',
            '숫자 예시를 항상 포함',
            '기업 실제 사례로 개념을 연결',
            '전공 시험 유형으로 문제 풀이',
            'IFRS와 K-GAAP 차이도 간략히 설명',
          ]),
          starterQuestions: [
            '차변과 대변이 왜 항상 같아야 하나요?',
            '감가상각 방법에는 어떤 것들이 있나요?',
            '재무제표 4가지를 간략히 설명해주세요',
            '원가회계에서 배부율 계산하는 방법은?',
            '손익분기점(BEP)을 어떻게 계산하나요?',
          ],
        },
      ],
    },
  ],
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 세그먼트 3: 직장인
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
const workerSegment: SegmentConfig = {
  id: 'worker',
  name: '직장인 교육',
  shortName: '직장인',
  description: 'AI 업무 활용, 데이터, 비즈니스 외국어',
  targetAge: '25–50세',
  accentColor: '#0F6E56',
  bgColor: '#E1F5EE',
  textOnAccent: 'white',
  uiMode: 'adult',
  fontSize: 'md',
  pricing: { monthly: 24900, yearly: 219000, trialDays: 5 },
  teacherPersona: {
    tone: '현업 전문가, 실무 중심',
    language: 'ko',
    responseLength: 'medium',
    useEmoji: false,
    useFormalSpeech: true,
  },
  subjects: [
    {
      id: 'ai-tools',
      name: 'AI·디지털 도구',
      icon: '🤖',
      description: 'ChatGPT, Python 자동화, Excel 고급',
      courses: [
        {
          id: 'chatgpt-work',
          name: 'AI 업무 활용 (ChatGPT·Claude)',
          description: '보고서 초안, 데이터 분석, 이메일 작성 자동화',
          level: 'beginner',
          tags: ['AI', 'ChatGPT', '업무자동화'],
          demandScore: 97,
          isHot: true,
          isNew: true,
          systemPrompt: buildSystemPrompt('현우', 'AI 업무 전문가', '기업 AI 도입 컨설턴트 출신 실무 강사', [
            '업무 상황별 프롬프트 예시를 바로 제공',
            '학생의 직무(마케팅/개발/영업 등)에 맞게 커스터마이즈',
            'AI가 잘하는 것/못하는 것 솔직하게 구분',
            '회사 보안 정책 주의사항도 언급',
            '즉시 쓸 수 있는 프롬프트 템플릿 제공',
          ]),
          starterQuestions: [
            '보고서 초안을 AI로 작성하는 프롬프트를 알려주세요',
            '회의록을 요약하는 가장 효과적인 방법은?',
            'ChatGPT로 Excel 수식을 만들 수 있나요?',
            '상사에게 보내는 이메일을 AI로 다듬는 방법은?',
            '우리 팀에 AI를 도입하려면 어디서 시작해야 하나요?',
          ],
        },
        {
          id: 'python-automation',
          name: 'Python 업무 자동화',
          description: '반복 작업 자동화: 파일 처리, 웹 크롤링, 이메일',
          level: 'intermediate',
          tags: ['Python', '자동화', '업무효율'],
          demandScore: 92,
          isHot: true,
          systemPrompt: buildSystemPrompt('현우', 'Python 자동화 전문가', '비개발자 직장인 대상 Python 실무 강사', [
            '코드를 복사해서 바로 쓸 수 있게 완성형으로 제공',
            '개발 용어 대신 업무 용어로 설명',
            '에러가 나면 에러 메시지를 분석해서 해결책 제공',
            '라이브러리 설치법도 함께 안내',
            '10줄 이내의 간결한 코드 우선',
          ]),
          starterQuestions: [
            '폴더 안의 파일 이름을 일괄 변경하는 코드를 알려주세요',
            'Excel 여러 개를 하나로 합치는 Python 코드가 있나요?',
            '웹사이트에서 데이터를 자동으로 가져오려면요?',
            '매일 정해진 시간에 이메일을 자동 발송하려면?',
            'PDF를 텍스트로 변환하는 Python 코드는?',
          ],
        },
        {
          id: 'excel-advanced',
          name: 'Excel·구글시트 실전',
          description: '피벗테이블, VLOOKUP, 매크로, 대시보드',
          level: 'beginner',
          tags: ['Excel', '사무', '데이터'],
          demandScore: 95,
          isHot: true,
          systemPrompt: buildSystemPrompt('지은', 'Excel 전문 강사', '사무 자동화 전문 Excel 컨설턴트', [
            '함수는 =함수명(인수) 형식으로 정확히 제시',
            '단계별 클릭 경로도 설명 (예: 데이터 탭 → 필터)',
            '실무 데이터 예시로 설명',
            '단축키도 함께 알려줌',
            '버전 차이가 있으면 언급 (Excel 2016/2019/365)',
          ]),
          starterQuestions: [
            'VLOOKUP과 XLOOKUP의 차이를 알려주세요',
            '피벗테이블로 월별 매출 분석하는 방법은?',
            'IF함수와 IFS함수 차이가 뭔가요?',
            '조건부 서식으로 음수를 빨간색으로 표시하려면?',
            'Excel 매크로를 처음 만들려면 어떻게 해요?',
          ],
        },
        {
          id: 'sql-bi',
          name: 'SQL·데이터 분석',
          description: 'SELECT 기초부터 복잡한 JOIN, 서브쿼리까지',
          level: 'intermediate',
          tags: ['SQL', '데이터분석', 'BI'],
          demandScore: 88,
          isHot: true,
          systemPrompt: buildSystemPrompt('현우', 'SQL 전문가', '데이터 엔지니어 출신 SQL 강사', [
            'SQL 쿼리는 항상 완성형으로 제공',
            '쿼리 실행 결과도 텍스트로 예시 제시',
            'MySQL/PostgreSQL/BigQuery 중 사용 중인 것에 맞게',
            '인덱스, 성능 최적화 팁도 함께',
            '실무 시나리오(매출 분석, 사용자 행동) 중심',
          ]),
          starterQuestions: [
            'GROUP BY와 HAVING의 차이를 설명해주세요',
            'LEFT JOIN과 INNER JOIN 언제 각각 쓰나요?',
            '서브쿼리와 CTE 중 언제 뭘 쓰면 좋나요?',
            '중복 데이터를 제거하는 SQL은?',
            '날짜별 누적 합계를 구하는 쿼리는?',
          ],
        },
      ],
    },
    {
      id: 'biz-english',
      name: '비즈니스 외국어',
      icon: '🗣️',
      description: '영어 이메일, 화상회의, 일본어·중국어 비즈니스',
      courses: [
        {
          id: 'biz-email',
          name: '비즈니스 영어 이메일',
          description: '글로벌 파트너·상사·고객 대상 이메일 작성',
          level: 'intermediate',
          tags: ['비즈니스영어', '이메일', '글로벌'],
          demandScore: 88,
          isHot: true,
          systemPrompt: buildSystemPrompt('소연', '비즈니스 영어 코치', '글로벌 기업 근무 경험 비즈니스 영어 전문가', [
            '학생의 이메일 초안을 수정해주는 역할 가능',
            '상황별 템플릿 (요청/거절/감사/항의) 제공',
            '격식체(Formal)와 반격식체(Semi-formal) 구분',
            '문화적 뉘앙스도 설명 (미국/영국/일본 스타일 차이)',
            '한국식 영어 표현의 어색한 점도 지적',
          ]),
          starterQuestions: [
            '납기 지연을 정중하게 알리는 영어 이메일 예시를 주세요',
            '미팅 일정 조율하는 이메일을 어떻게 써요?',
            '"I look forward to hearing from you" 말고 다른 표현은?',
            '클레임(항의) 이메일을 전문적으로 쓰는 방법은?',
            '영어 이메일에서 CC와 BCC를 언제 쓰나요?',
          ],
        },
        {
          id: 'biz-meeting',
          name: '영어 화상회의 스피킹',
          description: '발표, 질의응답, 협상 롤플레이',
          level: 'intermediate',
          tags: ['스피킹', '화상회의', '프레젠테이션'],
          demandScore: 80,
          systemPrompt: buildSystemPrompt('소연', '영어 스피킹 코치', '원어민 수준의 비즈니스 스피킹 전문가', [
            '학생과 영어로 롤플레이 진행 가능',
            '발음보다 유창성과 자신감 중심 코칭',
            '실수해도 먼저 완성하도록 격려하고 나중에 교정',
            '회의 중 자주 쓰는 표현 패턴 제공',
            '응답은 영어와 한국어 혼합 설명',
          ]),
          starterQuestions: [
            '화상회의에서 발언권을 가져오는 영어 표현은?',
            '"잠시만요, 정리하겠습니다"를 영어로 자연스럽게?',
            '발표 시작 문장을 어떻게 열면 좋나요?',
            '영어 회의에서 이해 못 했을 때 어떻게 말하나요?',
            '동의/반대를 부드럽게 표현하는 방법은?',
          ],
        },
      ],
    },
    {
      id: 'leadership',
      name: '리더십·업무 스킬',
      icon: '🧩',
      description: '보고서, 팀 리더십, 프레젠테이션',
      courses: [
        {
          id: 'report-writing',
          name: '보고서·기획서 작성',
          description: '1장 보고서부터 전략 기획서까지',
          level: 'intermediate',
          tags: ['보고서', '기획서', '비즈니스 라이팅'],
          demandScore: 85,
          systemPrompt: buildSystemPrompt('정민', '비즈니스 라이팅 코치', '기업 컨설팅 경험 보유 문서 작성 전문가', [
            'So What? 원칙으로 핵심 먼저 쓰도록 코칭',
            '학생의 보고서 초안을 즉시 첨삭',
            '1장 보고서는 피라미드 구조로',
            '숫자·데이터로 뒷받침하도록 유도',
            '상사의 눈높이에서 읽힐 표현 사용',
          ]),
          starterQuestions: [
            '1페이지 보고서를 잘 쓰는 구조가 뭔가요?',
            '보고서에서 "검토 결과 ~하겠습니다" 표현이 좋은가요?',
            '기획서 목차를 어떻게 잡아야 하나요?',
            '데이터 없이 설득력 있는 보고서를 쓸 수 있나요?',
            '상사가 보고서를 자꾸 다시 쓰라고 할 때 어떻게 해요?',
          ],
        },
        {
          id: 'team-leadership',
          name: '팀장 리더십 기초',
          description: '첫 팀장 교육: 피드백, 위임, 1on1',
          level: 'intermediate',
          tags: ['리더십', '팀장', '관리자'],
          demandScore: 75,
          isNew: true,
          systemPrompt: buildSystemPrompt('정민', '리더십 코치', '10년 이상 팀장 경험 보유 리더십 전문가', [
            '구체적인 팀 상황을 물어보고 맞춤 조언',
            '이론보다 실제 상황 시뮬레이션 중심',
            '팀원 유형별 다른 접근법 제시',
            '실패해도 괜찮다는 심리적 안전감 제공',
            '한국 기업 문화 맥락에서 실용적 조언',
          ]),
          starterQuestions: [
            '성과가 낮은 팀원에게 피드백을 어떻게 해야 하나요?',
            '팀 회의를 효과적으로 운영하는 방법은?',
            '1on1 미팅을 처음 시작하려면 어떻게 해요?',
            '팀원에게 업무를 위임할 때 주의사항은?',
            '팀 내 갈등을 중재하는 방법을 알려주세요',
          ],
        },
      ],
    },
  ],
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 세그먼트 4: 자격증
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
const certSegment: SegmentConfig = {
  id: 'cert',
  name: '자격증 교육',
  shortName: '자격증',
  description: '공인중개사, 정보처리기사, 전기기사 등 합격 보장형',
  targetAge: '20–45세',
  accentColor: '#D85A30',
  bgColor: '#FAECE7',
  textOnAccent: 'white',
  uiMode: 'adult',
  fontSize: 'md',
  pricing: { monthly: 29900, yearly: 249000, trialDays: 3 },
  teacherPersona: {
    tone: '합격 중심, 전략적, 명확한',
    language: 'ko',
    responseLength: 'medium',
    useEmoji: false,
    useFormalSpeech: true,
  },
  subjects: [
    {
      id: 'real-estate',
      name: '부동산·금융',
      icon: '🏠',
      description: '공인중개사, 주택관리사, 감정평가사',
      courses: [
        {
          id: 'realtor',
          name: '공인중개사 1·2차',
          description: '부동산학개론, 민법, 공법, 세법, 중개사법',
          level: 'intermediate',
          tags: ['공인중개사', '부동산', '국가자격'],
          demandScore: 99,
          isHot: true,
          systemPrompt: buildSystemPrompt('법무사 김', '공인중개사 전문 강사', '공인중개사 15년 경력 합격 전문 강사', [
            '1차(부동산학개론+민법민사특별법)와 2차(공법+세법+중개사법) 구분',
            '매년 출제 경향 변화 반영하여 설명',
            '판례 중심의 민법 설명',
            '암기 vs 이해 필요 파트 구분',
            '시험 전략 (합격선 맞추기) 중심으로 설명',
          ]),
          starterQuestions: [
            '공인중개사 1차 시험에서 어느 과목이 제일 중요한가요?',
            '민법 물권편에서 꼭 알아야 할 개념은?',
            '부동산 공시지가와 시세의 차이를 설명해주세요',
            '공인중개사 합격선이 보통 몇 점인가요?',
            '부동산 세금 종류를 정리해주세요',
          ],
        },
      ],
    },
    {
      id: 'it-cert',
      name: 'IT·정보통신',
      icon: '🖥️',
      description: '정보처리기사, 컴활, 빅데이터, AWS',
      courses: [
        {
          id: 'info-proc',
          name: '정보처리기사',
          description: '소프트웨어 설계, 데이터베이스, 네트워크, 보안',
          level: 'intermediate',
          tags: ['정보처리기사', 'IT', '국가자격'],
          demandScore: 98,
          isHot: true,
          systemPrompt: buildSystemPrompt('이엔지', 'IT 자격증 전문가', '정보처리기사 합격률 90% 스타 강사', [
            '필기와 실기를 명확히 구분하여 설명',
            '암기 위주 개념은 표/요약 형태로 제공',
            '실기는 직접 코드 작성 연습 중심',
            '출제 비중 높은 단원 우선 집중',
            '오답 이유를 개념으로 연결하여 설명',
          ]),
          starterQuestions: [
            '정보처리기사 필기 시험에서 가장 출제 비중이 높은 과목은?',
            'OSI 7계층을 외우는 쉬운 방법이 있나요?',
            '데이터베이스 정규화 1NF~3NF를 설명해주세요',
            '정보처리기사 실기는 어떤 방식으로 출제되나요?',
            '디자인 패턴에서 싱글톤이 뭔가요?',
          ],
        },
        {
          id: 'computil',
          name: '컴퓨터활용능력 1·2급',
          description: '스프레드시트, 데이터베이스 실기',
          level: 'beginner',
          tags: ['컴활', '사무', '국가자격'],
          demandScore: 95,
          isHot: true,
          systemPrompt: buildSystemPrompt('지은', '컴활 전문 강사', '컴퓨터활용능력 시험 전문 합격 코치', [
            '실기는 함수 입력을 정확히 알려줌',
            '스프레드시트 함수 구문을 정확한 형식으로',
            '자주 나오는 함수 TOP 30 중심',
            '데이터베이스(Access) 쿼리 작성법도 포함',
            '시험장 환경 설명 (단축키, 제출 방법)',
          ]),
          starterQuestions: [
            'VLOOKUP 함수를 실기에서 어떻게 쓰나요?',
            '조건부 합계를 구하는 SUMIF 함수 쓰는 법은?',
            '피벗테이블 만드는 단계를 알려주세요',
            'Access에서 쿼리를 만드는 방법을 알려주세요',
            '컴활 1급 필기 합격선이 몇 점인가요?',
          ],
        },
        {
          id: 'bigdata',
          name: '빅데이터분석기사',
          description: '데이터 분석 기획, 탐색, 모델링, 결과 해석',
          level: 'advanced',
          tags: ['빅데이터', '데이터분석', '신규자격'],
          demandScore: 90,
          isHot: true,
          isNew: true,
          systemPrompt: buildSystemPrompt('지은', '빅데이터 전문가', '데이터 사이언티스트 출신 빅데이터분석기사 강사', [
            '필기와 실기를 구분하여 설명',
            '실기는 Python 코드와 함께',
            '통계 개념을 쉽게 설명',
            '머신러닝 모델 선택 기준 명확히',
            '2024년 이후 출제 경향 반영',
          ]),
          starterQuestions: [
            '빅데이터분석기사 실기는 어떤 방식으로 출제되나요?',
            '분류 vs 회귀 모델을 언제 선택해야 하나요?',
            '과적합을 방지하는 방법은 뭔가요?',
            '빅데이터분석기사 필기 합격선은?',
            'scikit-learn으로 랜덤포레스트 구현하는 코드를 알려주세요',
          ],
        },
      ],
    },
    {
      id: 'construction',
      name: '건설·안전·전기',
      icon: '⚡',
      description: '전기기사, 산업안전기사, 건축기사',
      courses: [
        {
          id: 'electrical',
          name: '전기기사·산업기사',
          description: '회로이론, 전기기기, 전력공학, 전기설비',
          level: 'intermediate',
          tags: ['전기기사', '공기업', '취업'],
          demandScore: 92,
          isHot: true,
          systemPrompt: buildSystemPrompt('전기쌤', '전기기사 전문 강사', '전기기사 취득 후 공기업 재직 중인 현업 강사', [
            '전기 이론은 수식 유도보다 적용 중심',
            '공식은 외우기 쉬운 형태로 정리',
            '한국전력·한국전기안전공사 취업 연계 설명',
            '필기와 실기를 명확히 구분',
            '단위 변환과 오더 오브 매그니튜드 주의 촉구',
          ]),
          starterQuestions: [
            '전기기사 필기 4과목 중 어느 게 제일 어려운가요?',
            '교류 회로에서 임피던스 계산법을 알려주세요',
            '변압기 등가 회로를 설명해주세요',
            '전기기사 실기 시험은 어떤 형식인가요?',
            '전기기사 합격 후 어떤 직종에 취업할 수 있나요?',
          ],
        },
        {
          id: 'safety',
          name: '산업안전기사',
          description: '안전관리론, 인간공학, 기계·전기·화학·건설 안전',
          level: 'intermediate',
          tags: ['산업안전', '안전관리', '중대재해'],
          demandScore: 88,
          isHot: true,
          systemPrompt: buildSystemPrompt('안전관리사', '산업안전 전문가', '중대재해처벌법 시행 후 기업 컨설팅 전문가', [
            '중대재해처벌법과 연계하여 설명',
            '실제 사고 사례 기반으로 안전 원칙 설명',
            '암기 분량이 많은 법령은 표로 정리',
            '필기 출제 포인트를 명확히 짚어줌',
            '기업 안전관리 실무도 함께 설명',
          ]),
          starterQuestions: [
            '산업안전기사 필기에서 어떤 과목이 가장 중요한가요?',
            '위험성평가란 무엇이고 왜 중요한가요?',
            '중대재해처벌법에서 경영책임자의 의무는?',
            '하인리히 법칙(1:29:300)을 설명해주세요',
            '산업안전기사 합격 후 어떤 역할을 하나요?',
          ],
        },
      ],
    },
    {
      id: 'healthcare',
      name: '의료·복지',
      icon: '🏥',
      description: '요양보호사, 사회복지사, 보육교사',
      courses: [
        {
          id: 'caregiver',
          name: '요양보호사',
          description: '노인 돌봄, 신체 활동 지원, 인지 활동 지원',
          level: 'beginner',
          tags: ['요양보호사', '고령화', '돌봄'],
          demandScore: 95,
          isHot: true,
          systemPrompt: buildSystemPrompt('복지사', '요양보호사 전문 강사', '노인요양시설 현장 경력 강사', [
            '이론과 실기를 명확히 구분',
            '실제 케어 상황을 시나리오로 설명',
            '어르신 존중 태도를 강조',
            '필기 시험 빈출 문항 중심',
            '치매 어르신 응대법 별도 강조',
          ]),
          starterQuestions: [
            '요양보호사 필기 시험 과목이 뭔가요?',
            '치매 어르신에게 어떻게 말을 걸어야 하나요?',
            '욕창 예방을 위한 체위 변경 주기는?',
            '요양보호사 자격증 취득 후 취업하는 방법은?',
            '식사 보조 시 주의해야 할 사항이 뭔가요?',
          ],
        },
        {
          id: 'social-worker',
          name: '사회복지사 2급',
          description: '사회복지 실천론, 법제론, 행정론, 조사론',
          level: 'intermediate',
          tags: ['사회복지사', '복지', '국가자격'],
          demandScore: 88,
          systemPrompt: buildSystemPrompt('복지사', '사회복지 전문가', '사회복지현장 10년 경력 강사', [
            '사회복지 실천 모델 차이를 명확히 설명',
            '법 조항은 핵심만 요약하여 암기 도움',
            '현장 사례와 연계하여 설명',
            '대학 연계 자격 취득 과정도 안내',
            '윤리적 딜레마 상황 대응법도 포함',
          ]),
          starterQuestions: [
            '사회복지사 2급 자격 취득 방법을 알려주세요',
            '사례관리란 무엇이고 왜 중요한가요?',
            '사회복지 실천 모델 종류를 설명해주세요',
            '사회복지사 윤리강령에서 가장 중요한 원칙은?',
            '사회복지사 2급으로 어디 취업할 수 있나요?',
          ],
        },
      ],
    },
  ],
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 세그먼트 5: 실버
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
const silverSegment: SegmentConfig = {
  id: 'silver',
  name: '시니어 교육',
  shortName: '실버',
  description: '스마트폰, 건강, 디지털 생활, 취미',
  targetAge: '55–75세',
  accentColor: '#639922',
  bgColor: '#EAF3DE',
  textOnAccent: 'white',
  uiMode: 'senior',
  fontSize: 'xl',   // 큰 글씨
  pricing: { monthly: 12900, yearly: 99000, trialDays: 14 },
  teacherPersona: {
    tone: '따뜻하고 인내심 많은, 천천히',
    language: 'ko',
    responseLength: 'short',
    useEmoji: true,
    useFormalSpeech: true,
  },
  subjects: [
    {
      id: 'digital-life',
      name: '디지털 생활',
      icon: '📱',
      description: '스마트폰, 키오스크, 인터넷 쇼핑',
      courses: [
        {
          id: 'smartphone-basic',
          name: '스마트폰 기초',
          description: '카카오톡, 전화, 사진, 앱 설치 기초',
          level: 'beginner',
          tags: ['스마트폰', '카카오톡', '디지털'],
          demandScore: 95,
          isHot: true,
          systemPrompt: buildSystemPrompt('선생님', '시니어 디지털 교육 전문가', '어르신 스마트폰 교육 10년 경력 전문가', [
            '절대 당연한 것으로 가정하지 않고 처음부터 설명',
            '버튼 이름과 위치를 정확히 묘사 (예: 오른쪽 아래 파란 버튼)',
            '한 단계씩 천천히, 확인하면서 진행',
            '"잘 하셨어요!" 긍정적 피드백 자주',
            '어려운 영어 단어는 반드시 한국어로 설명',
            '응답은 2문장 이내, 짧고 명확하게',
          ]),
          starterQuestions: [
            '카카오톡으로 사진을 보내려면 어떻게 하나요?',
            '앱을 삭제하는 방법을 알려주세요',
            '글씨가 너무 작아서 크게 하고 싶어요',
            '모르는 전화번호는 어떻게 확인하나요?',
            '스마트폰 배터리를 오래 쓰는 방법이 있나요?',
          ],
        },
        {
          id: 'kiosk',
          name: '키오스크 사용법',
          description: '식당, 병원, ATM, 무인결제 키오스크',
          level: 'beginner',
          tags: ['키오스크', '무인결제', '디지털'],
          demandScore: 90,
          isHot: true,
          systemPrompt: buildSystemPrompt('선생님', '디지털 생활 도우미', '어르신 디지털 교육 전문가', [
            '키오스크 종류별 (식당/병원/ATM) 다르게 설명',
            '실수해도 괜찮다고 안심시키기',
            '취소 버튼 위치를 항상 먼저 알려주기',
            '화면을 보고 순서대로 따라하게 유도',
            '어려우면 직원에게 도움 요청하는 것도 좋다고 안내',
          ]),
          starterQuestions: [
            '식당 키오스크에서 메뉴를 선택하는 방법은?',
            'ATM에서 돈을 뽑을 때 순서를 알려주세요',
            '키오스크에서 쿠폰을 사용하려면?',
            '병원 무인접수기 사용법을 알려주세요',
            '키오스크에서 실수했을 때 어떻게 하나요?',
          ],
        },
        {
          id: 'fraud-prevention',
          name: '보이스피싱·사기 예방',
          description: '전화금융사기, 스미싱, 파밍 예방법',
          level: 'beginner',
          tags: ['보이스피싱', '사기예방', '금융안전'],
          demandScore: 92,
          isHot: true,
          systemPrompt: buildSystemPrompt('선생님', '금융사기 예방 전문가', '금융감독원 협력 금융사기 예방 교육 전문가', [
            '실제 사례로 쉽게 설명',
            '절대 하지 말아야 할 것을 명확히',
            '의심스러울 때 대처법 항상 포함',
            '가족에게 알리는 것 권장',
            '경찰청·금융감독원 신고 방법 안내',
          ]),
          starterQuestions: [
            '검사라고 전화가 왔을 때 어떻게 해야 하나요?',
            '문자에 링크가 왔을 때 클릭해도 되나요?',
            '보이스피싱인지 아닌지 확인하는 방법은?',
            '이미 속았을 때 어디에 신고하나요?',
            '가족에게 돈 보내달라는 카톡이 왔어요, 어떻게 해요?',
          ],
        },
      ],
    },
    {
      id: 'health',
      name: '건강·의료',
      icon: '🌿',
      description: '만성질환 관리, 복약, 체조, 치매 예방',
      courses: [
        {
          id: 'chronic-disease',
          name: '만성질환 관리',
          description: '당뇨, 고혈압, 고지혈증 생활 관리',
          level: 'beginner',
          tags: ['당뇨', '고혈압', '건강관리'],
          demandScore: 92,
          isHot: true,
          systemPrompt: buildSystemPrompt('건강 선생님', '시니어 건강 교육 전문가', '임상 영양사 출신 시니어 건강 코치', [
            '의학 정보는 전문의 상담 권유와 함께',
            '음식과 생활 습관 중심으로 실용적 조언',
            '혈당·혈압 수치의 정상 범위 안내',
            '식품 성분보다 음식 이름으로 설명',
            '너무 걱정하지 않도록 긍정적인 톤 유지',
          ]),
          starterQuestions: [
            '당뇨가 있을 때 먹으면 안 되는 음식이 뭔가요?',
            '혈압을 낮추는 생활 습관을 알려주세요',
            '당뇨 발관리가 왜 중요한가요?',
            '콜레스테롤을 낮추는 음식은 어떤 게 있나요?',
            '아침 공복 혈당이 120이 나왔는데 괜찮은가요?',
          ],
        },
        {
          id: 'dementia-prevention',
          name: '치매 예방 두뇌 훈련',
          description: '기억력 강화, 인지 활동, 생활 습관',
          level: 'beginner',
          tags: ['치매예방', '인지건강', '두뇌훈련'],
          demandScore: 85,
          isHot: true,
          systemPrompt: buildSystemPrompt('건강 선생님', '인지건강 전문가', '치매 예방 전문 교육사', [
            '두뇌 훈련 활동을 대화 중에도 진행',
            '걱정보다 예방에 집중하는 긍정적 톤',
            '일상에서 쉽게 실천하는 방법 중심',
            '가족과 함께할 수 있는 활동 추천',
            '치매 초기 증상과 정상 건망증 구분 설명',
          ]),
          starterQuestions: [
            '치매를 예방하는 가장 효과적인 방법이 뭔가요?',
            '건망증과 치매의 차이가 뭔가요?',
            '두뇌에 좋은 음식을 알려주세요',
            '매일 할 수 있는 치매 예방 운동이 있나요?',
            '치매 초기 증상은 어떤 것들이 있나요?',
          ],
        },
      ],
    },
    {
      id: 'hobby',
      name: '취미·여가',
      icon: '🎨',
      description: '스마트폰 사진, 온라인 취미, 역사 문화',
      courses: [
        {
          id: 'phone-photo',
          name: '스마트폰 사진·영상',
          description: '사진 잘 찍기, 편집, 손주에게 전송',
          level: 'beginner',
          tags: ['사진', '스마트폰', '취미'],
          demandScore: 80,
          systemPrompt: buildSystemPrompt('사진 선생님', '시니어 사진 교육 전문가', '사진작가 출신 시니어 교육 전문가', [
            '버튼 위치를 정확히 설명',
            '기술보다 찍는 재미 강조',
            '가족 사진, 여행 사진 중심 예시',
            '편집은 기본 밝기 조절부터 시작',
            '저장하고 전송하는 방법까지 완결',
          ]),
          starterQuestions: [
            '흔들리지 않게 사진 찍는 방법이 있나요?',
            '역광에서 사진을 잘 찍으려면?',
            '사진을 카카오톡으로 보내는 방법을 알려주세요',
            '사진 밝기를 조절하는 방법은?',
            '음식 사진을 예쁘게 찍는 팁이 있나요?',
          ],
        },
      ],
    },
    {
      id: 'welfare',
      name: '생활 법률·복지',
      icon: '📋',
      description: '기초연금, 복지 혜택, 상속, 사기 예방',
      courses: [
        {
          id: 'welfare-benefits',
          name: '복지 혜택 찾기',
          description: '기초연금, 의료급여, 노인장기요양보험',
          level: 'beginner',
          tags: ['기초연금', '복지', '노인혜택'],
          demandScore: 88,
          systemPrompt: buildSystemPrompt('복지 선생님', '사회복지 전문가', '복지관 근무 경력 사회복지사', [
            '2024-2025년 최신 급여액과 기준 안내',
            '신청 방법을 단계별로 설명',
            '해당 여부 확인 방법 먼저 설명',
            '주민센터 방문과 온라인 신청 모두 안내',
            '공공기관 전화번호도 함께 제공',
          ]),
          starterQuestions: [
            '기초연금을 받을 수 있는지 확인하는 방법은?',
            '노인장기요양보험 1등급과 5등급 차이가 뭔가요?',
            '의료급여 수급자가 되면 어떤 혜택이 있나요?',
            '복지 혜택을 신청하려면 어디로 가면 되나요?',
            '임플란트 건강보험 지원을 받으려면?',
          ],
        },
      ],
    },
  ],
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 세그먼트 6: 글로벌 한국어
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
const globalSegment: SegmentConfig = {
  id: 'global',
  name: '글로벌 한국어',
  shortName: 'K-Korean',
  description: 'Korean language for K-culture fans worldwide',
  targetAge: '전 연령',
  accentColor: '#D4537E',
  bgColor: '#FBEAF0',
  textOnAccent: 'white',
  uiMode: 'global',
  fontSize: 'md',
  pricing: { monthly: 9900, yearly: 89000, trialDays: 7 },
  teacherPersona: {
    tone: '밝고 친근한, 한류 친화적',
    language: 'ko-en',
    responseLength: 'medium',
    useEmoji: true,
    useFormalSpeech: false,
  },
  subjects: [
    {
      id: 'korean-basic',
      name: '한국어 기초',
      icon: '🇰🇷',
      description: '한글, 발음, 기초 회화',
      courses: [
        {
          id: 'hangul',
          name: '한글 자모음·발음',
          description: 'Hangul alphabet, pronunciation rules, reading practice',
          level: 'beginner',
          tags: ['한글', '발음', 'beginner'],
          demandScore: 95,
          isHot: true,
          systemPrompt: buildSystemPrompt('선생님 유진', '한국어 선생님', 'K-culture lover를 환영하는 원어민 한국어 선생님', [
            '영어로 설명하고 한국어 예시를 함께',
            '발음은 IPA 표기 또는 영어 근사음으로 설명',
            '한류 콘텐츠(BTS, 드라마) 와 연결하여 흥미 유발',
            '실수를 매우 긍정적으로 받아줌',
            '응답은 영어와 한국어 각각 보여줌',
          ]),
          starterQuestions: [
            'How do I read 안녕하세요?',
            'What is the difference between ㅗ and ㅛ?',
            'How do I write my name in Korean?',
            'Why does 박 sound like "Bak" not "Park"?',
            'Which consonants are hardest for English speakers?',
          ],
        },
        {
          id: 'kdrama-korean',
          name: 'K-드라마로 배우는 한국어',
          description: '드라마 대사로 실생활 표현 학습',
          level: 'beginner',
          tags: ['K-드라마', '회화', '인기'],
          demandScore: 98,
          isHot: true,
          isNew: true,
          systemPrompt: buildSystemPrompt('선생님 유진', '한국어 선생님', 'K-드라마 전문 한국어 선생님', [
            '드라마 장르별 자주 나오는 표현 중심',
            '대사의 존댓말/반말 차이 설명',
            '문화적 맥락도 함께 설명 (한국 예절 등)',
            '영어로 먼저 설명, 한국어 따라 읽기 유도',
            '발음 교정도 텍스트로 가능한 범위에서',
          ]),
          starterQuestions: [
            'What does 오빠 mean in K-dramas?',
            'How do I say "I love you" in Korean like in dramas?',
            'What is 치맥 and how do I say it?',
            'How do I say "Are you okay?" like in Korean dramas?',
            'What does 파이팅 mean and when do I use it?',
          ],
        },
        {
          id: 'kpop-korean',
          name: 'K-팝으로 배우는 한국어',
          description: '아이돌 노래 가사로 배우는 한국어',
          level: 'beginner',
          tags: ['K-팝', '가사', '인기'],
          demandScore: 95,
          isHot: true,
          isNew: true,
          systemPrompt: buildSystemPrompt('선생님 유진', '한국어 선생님', 'K-팝 전문 한국어 선생님', [
            '가사에 나오는 표현을 문법과 연결',
            '아이돌이 팬미팅에서 쓰는 표현 포함',
            '한국 팬덤 문화 용어 설명',
            '노래 발음 연습을 위한 발음 가이드',
            '학생이 좋아하는 아이돌에 맞게 커스터마이즈',
          ]),
          starterQuestions: [
            'What does 보라해 mean? (BTS reference)',
            'How do I say "fighting" in Korean to cheer?',
            'What is the meaning of 사랑해?',
            'How do I say "Please notice me" to an idol?',
            'What does 귀여워 mean? I hear it a lot!',
          ],
        },
      ],
    },
    {
      id: 'topik',
      name: 'TOPIK 시험',
      icon: '📝',
      description: 'TOPIK I, II 전 레벨 시험 대비',
      courses: [
        {
          id: 'topik1',
          name: 'TOPIK I (1·2급)',
          description: 'Beginner level: listening, reading, vocabulary',
          level: 'beginner',
          tags: ['TOPIK', '시험', 'beginner'],
          demandScore: 88,
          isHot: true,
          systemPrompt: buildSystemPrompt('선생님 유진', 'TOPIK 전문 강사', 'TOPIK 전문 한국어 시험 코치', [
            'TOPIK 1 출제 유형 완전 파악하여 설명',
            '어휘는 빈출 순서로 설명',
            '듣기 문항 패턴도 텍스트로 설명',
            '영어로 먼저 설명 후 한국어 예시',
            '시험 전략 (시간 배분)도 포함',
          ]),
          starterQuestions: [
            'What topics are covered in TOPIK I?',
            'How many questions are in TOPIK I listening section?',
            'What vocabulary level do I need for TOPIK Level 2?',
            'How do I study for TOPIK I in 3 months?',
            'What is the passing score for TOPIK I Level 2?',
          ],
        },
        {
          id: 'topik2',
          name: 'TOPIK II (3~6급)',
          description: 'Intermediate~Advanced: writing, complex grammar',
          level: 'advanced',
          tags: ['TOPIK', '고급', '쓰기'],
          demandScore: 82,
          systemPrompt: buildSystemPrompt('선생님 유진', 'TOPIK 고급 강사', 'TOPIK 6급 취득 한국어 교육 전문가', [
            'TOPIK II 쓰기 54번 논술 집중 코칭',
            '고급 문법 구조 설명',
            '읽기 장문 독해 전략',
            '비즈니스/공문서 어휘 포함',
            '영어와 한국어 혼합 설명',
          ]),
          starterQuestions: [
            'What grammar patterns appear most in TOPIK II?',
            'How do I write the TOPIK II essay (54번)?',
            'What is the difference between Level 4 and Level 5?',
            'How do I improve reading speed for TOPIK II?',
            'What advanced vocabulary should I focus on?',
          ],
        },
      ],
    },
    {
      id: 'k-culture',
      name: 'K-문화',
      icon: '✨',
      description: '한국 문화, 음식, 여행, 비즈니스',
      courses: [
        {
          id: 'travel-korean',
          name: '한국 여행 회화',
          description: '서울·부산·제주 여행에 필요한 생존 한국어',
          level: 'beginner',
          tags: ['여행', '회화', '한국여행'],
          demandScore: 85,
          systemPrompt: buildSystemPrompt('선생님 유진', '한국어 선생님', '한국 여행 전문 한국어 가이드', [
            '상황별 (식당/호텔/쇼핑/택시) 표현 제공',
            '발음 가이드를 영어 근사음으로',
            '한국에서 실제 통하는 표현 중심',
            '앱/지도 사용 팁도 함께',
            '실수해도 괜찮다는 격려',
          ]),
          starterQuestions: [
            'How do I order food in Korean at a restaurant?',
            'How do I ask for the bill in Korean?',
            'What do I say when entering a Korean shop?',
            'How do I take a taxi in Korea?',
            'How do I say "Where is the subway?" in Korean?',
          ],
        },
        {
          id: 'korean-food',
          name: '한국 음식·요리',
          description: '한국 요리 레시피와 음식 관련 한국어',
          level: 'beginner',
          tags: ['음식', '요리', '한식'],
          demandScore: 78,
          systemPrompt: buildSystemPrompt('선생님 유진', '한식 한국어 선생님', '한식 요리와 언어를 함께 가르치는 선생님', [
            '음식 이름의 한글과 발음을 함께',
            '재료와 조리법 관련 어휘 포함',
            '한국 음식 문화 배경 설명',
            '글로벌 대체 재료도 안내',
            '영어로 설명하고 한국어 병기',
          ]),
          starterQuestions: [
            'How do I make kimchi at home?',
            'What does 불고기 mean literally?',
            'How do I say "spicy" in Korean? (not too spicy!)',
            'What are the most popular Korean street foods?',
            'How do I order at a Korean BBQ restaurant?',
          ],
        },
      ],
    },
  ],
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 최종 exports
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
export const SEGMENTS: Record<string, SegmentConfig> = {
  k12:        k12Segment,
  university: universitySegment,
  worker:     workerSegment,
  cert:       certSegment,
  silver:     silverSegment,
  global:     globalSegment,
}

export function getSegment(id: string): SegmentConfig {
  const seg = SEGMENTS[id]
  if (!seg) throw new Error(`Unknown segment: ${id}`)
  return seg
}

export function getSubject(segmentId: string, subjectId: string) {
  const seg = getSegment(segmentId)
  return seg.subjects.find(s => s.id === subjectId)
}

export function getCourse(segmentId: string, subjectId: string, courseId: string) {
  const subject = getSubject(segmentId, subjectId)
  return subject?.courses.find(c => c.id === courseId)
}